CONF_ARCHIVE = "RBU4P_ARCHIVE"
CONF_DESTINATION = "RBU4P_DESTINATION"
CONF_FORCE = "RBU4P_FORCE"
CONF_INSECURE = "RBU4P_INSECURE"
CONF_ON_BAD_ENDPOINT = "RBU4P_ON_BAD_ENDPOINT"
CONF_TOKEN = "RBU4P_TOKEN"
CONF_URL = "RBU4P_URL"

DEFAULT_ON_BAD_ENDPOINT = "skip"
